name: calculadora_imc
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  provider: ^6.0.5
  sqlite3_flutter_libs:

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite: ^2.0.0
  flutter_lints: ^2.0.0
  sqflite_common_ffi:

flutter:
  uses-material-design: true